services:
  template-mind:
    restart: always
    build:
      context: ..
      args:
        - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@onesolar-db:5432/${POSTGRES_DB}
    image: jonaszell/template-mind
    container_name: template-mind
    depends_on:
      - template-db
    networks:
      - template

networks:
  template:
    name: template-network
    external: true